paginate: 5
paginate_path: "/news/page:num/"
kramdown:
  parse_block_html: true
plugins:
  - jekyll-paginate
  - jekyll-autoprefixer

site_name: Resistance Lab
site_description: Collective against state violence

theme_primary_colour: "#C1272D"
theme_secondary_colour: "#000000"

contact_email: info@resistancelab.network
contact_twitter: ResLabMcr
contact_instagram: ResLabMcr
contact_github: Resistance_Lab

google_analytics:
